language: android

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - platform-tools
    - tools
    - build-tools-30.0.2
    - android-30

jdk:
    - oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-30"

script:
  ./gradlew build